import { ReactNode } from 'react'
import NavComponent from '@/components/nav/NavComponent'
import './globals.scss'
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({children,}: { children: ReactNode; }) {
    return (
        <html lang="en">
        <head/>
        <body>
        <NavComponent />
        {children}
        </body>
        </html>
    );
}
